import type { KeywordInfo } from '../types';

/**
 * The ZX Spectrum (48K) BASIC keyword/token table. Tokens occupy 0xA5–0xFF
 * (165–255); each keyword is a single byte in the tokenized program. The
 * 128K-only tokens SPECTRUM (0xA3) and PLAY (0xA4) are intentionally omitted.
 *
 * Several keywords are two words on the real machine (GO TO, GO SUB, DEF FN,
 * OPEN #, CLOSE #); they are stored here in their canonical listing form. The
 * tokenizer also accepts the glued spellings (GOTO, GOSUB).
 */
export const spectrumKeywords: KeywordInfo[] = [
  {
    word: 'RND',
    token: 0xa5,
    kind: 'function',
    signature: 'RND',
    doc: 'Random number in [0,1).',
  },
  {
    word: 'INKEY$',
    token: 0xa6,
    kind: 'function',
    signature: 'INKEY$',
    doc: 'Currently pressed key as a string, "" if none. The heart of every game loop.',
  },
  {
    word: 'PI',
    token: 0xa7,
    kind: 'function',
    signature: 'PI',
    doc: '3.14159…',
  },
  {
    word: 'FN',
    token: 0xa8,
    kind: 'function',
    signature: 'FN a(args)',
    doc: 'Call a user-defined function declared with DEF FN.',
  },
  {
    word: 'POINT',
    token: 0xa9,
    kind: 'function',
    signature: 'POINT (x,y)',
    doc: '1 if the pixel at x,y is ink, else 0.',
  },
  {
    word: 'SCREEN$',
    token: 0xaa,
    kind: 'function',
    signature: 'SCREEN$ (row,col)',
    doc: 'Character shown at a screen position (recognises the font).',
  },
  {
    word: 'ATTR',
    token: 0xab,
    kind: 'function',
    signature: 'ATTR (row,col)',
    doc: 'Attribute byte (ink/paper/bright/flash) at a screen cell.',
  },
  {
    word: 'AT',
    token: 0xac,
    kind: 'operator',
    signature: 'PRINT AT row,col;',
    doc: 'Position the print cursor: row 0-21, column 0-31.',
  },
  {
    word: 'TAB',
    token: 0xad,
    kind: 'operator',
    signature: 'PRINT TAB n;',
    doc: 'Move print position to column n.',
  },
  {
    word: 'VAL$',
    token: 0xae,
    kind: 'function',
    signature: 'VAL$ s$',
    doc: 'Evaluate s$ as a string expression.',
  },
  {
    word: 'CODE',
    token: 0xaf,
    kind: 'function',
    signature: 'CODE s$',
    doc: 'Character code of the first character of s$.',
  },
  {
    word: 'VAL',
    token: 0xb0,
    kind: 'function',
    signature: 'VAL s$',
    doc: 'Evaluate s$ as a numeric expression.',
  },
  {
    word: 'LEN',
    token: 0xb1,
    kind: 'function',
    signature: 'LEN s$',
    doc: 'Length of string s$.',
  },
  {
    word: 'SIN',
    token: 0xb2,
    kind: 'function',
    signature: 'SIN x',
    doc: 'Sine (radians).',
  },
  {
    word: 'COS',
    token: 0xb3,
    kind: 'function',
    signature: 'COS x',
    doc: 'Cosine (radians).',
  },
  {
    word: 'TAN',
    token: 0xb4,
    kind: 'function',
    signature: 'TAN x',
    doc: 'Tangent (radians).',
  },
  {
    word: 'ASN',
    token: 0xb5,
    kind: 'function',
    signature: 'ASN x',
    doc: 'Arcsine.',
  },
  {
    word: 'ACS',
    token: 0xb6,
    kind: 'function',
    signature: 'ACS x',
    doc: 'Arccosine.',
  },
  {
    word: 'ATN',
    token: 0xb7,
    kind: 'function',
    signature: 'ATN x',
    doc: 'Arctangent.',
  },
  {
    word: 'LN',
    token: 0xb8,
    kind: 'function',
    signature: 'LN x',
    doc: 'Natural logarithm.',
  },
  {
    word: 'EXP',
    token: 0xb9,
    kind: 'function',
    signature: 'EXP x',
    doc: 'e to the power x.',
  },
  {
    word: 'INT',
    token: 0xba,
    kind: 'function',
    signature: 'INT x',
    doc: 'Largest integer ≤ x (floors negatives).',
  },
  {
    word: 'SQR',
    token: 0xbb,
    kind: 'function',
    signature: 'SQR x',
    doc: 'Square root.',
  },
  {
    word: 'SGN',
    token: 0xbc,
    kind: 'function',
    signature: 'SGN x',
    doc: 'Sign of x: -1, 0 or 1.',
  },
  {
    word: 'ABS',
    token: 0xbd,
    kind: 'function',
    signature: 'ABS x',
    doc: 'Absolute value.',
  },
  {
    word: 'PEEK',
    token: 0xbe,
    kind: 'function',
    signature: 'PEEK addr',
    doc: 'Read a byte of memory.',
  },
  {
    word: 'IN',
    token: 0xbf,
    kind: 'function',
    signature: 'IN port',
    doc: 'Read a byte from a Z80 I/O port.',
  },
  {
    word: 'USR',
    token: 0xc0,
    kind: 'function',
    signature: 'USR addr',
    doc: 'Call machine code at addr; returns BC. USR "a" gives a UDG address.',
  },
  {
    word: 'STR$',
    token: 0xc1,
    kind: 'function',
    signature: 'STR$ x',
    doc: 'Number as a string.',
  },
  {
    word: 'CHR$',
    token: 0xc2,
    kind: 'function',
    signature: 'CHR$ n',
    doc: 'Character with code n.',
  },
  {
    word: 'NOT',
    token: 0xc3,
    kind: 'function',
    signature: 'NOT x',
    doc: 'Logical not: 1 if x=0, else 0.',
  },
  {
    word: 'BIN',
    token: 0xc4,
    kind: 'function',
    signature: 'BIN 1010',
    doc: 'Binary literal: BIN 1010 = 10.',
  },
  {
    word: 'OR',
    token: 0xc5,
    kind: 'operator',
    signature: 'a OR b',
    doc: 'Logical or.',
  },
  {
    word: 'AND',
    token: 0xc6,
    kind: 'operator',
    signature: 'a AND b',
    doc: 'Logical and.',
  },
  { word: '<=', token: 0xc7, kind: 'operator', doc: 'Less than or equal.' },
  { word: '>=', token: 0xc8, kind: 'operator', doc: 'Greater than or equal.' },
  { word: '<>', token: 0xc9, kind: 'operator', doc: 'Not equal.' },
  {
    word: 'LINE',
    token: 0xca,
    kind: 'operator',
    signature: 'SAVE "n" LINE l | INPUT LINE a$',
    doc: 'Auto-run line for SAVE; whole-line input for INPUT.',
  },
  {
    word: 'THEN',
    token: 0xcb,
    kind: 'operator',
    signature: 'IF cond THEN statements',
    doc: 'Statements after THEN run when the condition is true.',
  },
  {
    word: 'TO',
    token: 0xcc,
    kind: 'operator',
    signature: 'FOR v=a TO b | s$(a TO b)',
    doc: 'FOR range or string slice.',
  },
  {
    word: 'STEP',
    token: 0xcd,
    kind: 'operator',
    signature: 'FOR v=a TO b STEP c',
    doc: 'FOR loop increment.',
  },
  {
    word: 'DEF FN',
    token: 0xce,
    kind: 'command',
    signature: 'DEF FN a(x)=expr',
    doc: 'Define a user function; call it with FN.',
  },
  {
    word: 'CAT',
    token: 0xcf,
    kind: 'command',
    signature: 'CAT',
    doc: 'Catalogue (microdrive).',
  },
  {
    word: 'FORMAT',
    token: 0xd0,
    kind: 'command',
    signature: 'FORMAT "m";n',
    doc: 'Format/configure a channel (microdrive/RS232).',
  },
  {
    word: 'MOVE',
    token: 0xd1,
    kind: 'command',
    signature: 'MOVE "a" TO "b"',
    doc: 'Microdrive file move.',
  },
  {
    word: 'ERASE',
    token: 0xd2,
    kind: 'command',
    signature: 'ERASE "m";"name"',
    doc: 'Microdrive file erase.',
  },
  {
    word: 'OPEN #',
    token: 0xd3,
    kind: 'command',
    signature: 'OPEN #n,"s"',
    doc: 'Open a stream to a channel.',
  },
  {
    word: 'CLOSE #',
    token: 0xd4,
    kind: 'command',
    signature: 'CLOSE #n',
    doc: 'Close a stream.',
  },
  {
    word: 'MERGE',
    token: 0xd5,
    kind: 'command',
    signature: 'MERGE "name"',
    doc: 'Load a program merging it with the current one.',
  },
  {
    word: 'VERIFY',
    token: 0xd6,
    kind: 'command',
    signature: 'VERIFY "name"',
    doc: 'Verify a tape recording against memory.',
  },
  {
    word: 'BEEP',
    token: 0xd7,
    kind: 'command',
    signature: 'BEEP duration,pitch',
    doc: 'Sound a note: duration in seconds, pitch in semitones from middle C.',
  },
  {
    word: 'CIRCLE',
    token: 0xd8,
    kind: 'command',
    signature: 'CIRCLE x,y,r',
    doc: 'Draw a circle centred at x,y with radius r.',
  },
  {
    word: 'INK',
    token: 0xd9,
    kind: 'command',
    signature: 'INK n',
    doc: 'Set ink (foreground) colour 0-7 (8=transparent, 9=contrast).',
  },
  {
    word: 'PAPER',
    token: 0xda,
    kind: 'command',
    signature: 'PAPER n',
    doc: 'Set paper (background) colour 0-7.',
  },
  {
    word: 'FLASH',
    token: 0xdb,
    kind: 'command',
    signature: 'FLASH n',
    doc: 'Flashing on (1) / off (0).',
  },
  {
    word: 'BRIGHT',
    token: 0xdc,
    kind: 'command',
    signature: 'BRIGHT n',
    doc: 'Bright colours on (1) / off (0).',
  },
  {
    word: 'INVERSE',
    token: 0xdd,
    kind: 'command',
    signature: 'INVERSE n',
    doc: 'Swap ink and paper for printing (1) / normal (0).',
  },
  {
    word: 'OVER',
    token: 0xde,
    kind: 'command',
    signature: 'OVER n',
    doc: 'XOR printing over existing pixels (1) / normal (0).',
  },
  {
    word: 'OUT',
    token: 0xdf,
    kind: 'command',
    signature: 'OUT port,value',
    doc: 'Write a byte to a Z80 I/O port.',
  },
  {
    word: 'LPRINT',
    token: 0xe0,
    kind: 'command',
    signature: 'LPRINT items',
    doc: 'Print to the printer.',
  },
  {
    word: 'LLIST',
    token: 0xe1,
    kind: 'command',
    signature: 'LLIST [line]',
    doc: 'List to the printer.',
  },
  {
    word: 'STOP',
    token: 0xe2,
    kind: 'command',
    signature: 'STOP',
    doc: 'Halt with report 9; CONTINUE resumes at the next statement.',
  },
  {
    word: 'READ',
    token: 0xe3,
    kind: 'command',
    signature: 'READ v[,v…]',
    doc: 'Read the next DATA items into variables.',
  },
  {
    word: 'DATA',
    token: 0xe4,
    kind: 'command',
    signature: 'DATA item[,item…]',
    doc: 'Constants consumed by READ.',
  },
  {
    word: 'RESTORE',
    token: 0xe5,
    kind: 'command',
    signature: 'RESTORE [line]',
    doc: 'Reset the DATA pointer (optionally to a given line).',
  },
  {
    word: 'NEW',
    token: 0xe6,
    kind: 'command',
    signature: 'NEW',
    doc: 'Erase the program and variables.',
  },
  {
    word: 'BORDER',
    token: 0xe7,
    kind: 'command',
    signature: 'BORDER n',
    doc: 'Set the border colour 0-7.',
  },
  {
    word: 'CONTINUE',
    token: 0xe8,
    kind: 'command',
    signature: 'CONTINUE',
    doc: 'Resume after STOP or an error.',
  },
  {
    word: 'DIM',
    token: 0xe9,
    kind: 'command',
    signature: 'DIM a(n) | DIM a$(n,m)',
    doc: 'Declare an array (numeric or string).',
  },
  {
    word: 'REM',
    token: 0xea,
    kind: 'command',
    signature: 'REM comment',
    doc: 'Comment to end of line.',
  },
  {
    word: 'FOR',
    token: 0xeb,
    kind: 'command',
    signature: 'FOR v=a TO b [STEP c]',
    doc: 'Loop. Control variable is a single letter.',
  },
  {
    word: 'GO TO',
    token: 0xec,
    kind: 'command',
    signature: 'GO TO line',
    doc: 'Jump to a line number (computed targets allowed). Also accepts GOTO.',
  },
  {
    word: 'GO SUB',
    token: 0xed,
    kind: 'command',
    signature: 'GO SUB line',
    doc: 'Call a subroutine; RETURN comes back. Also accepts GOSUB.',
  },
  {
    word: 'INPUT',
    token: 0xee,
    kind: 'command',
    signature: 'INPUT [prompt;] v',
    doc: 'Read values from the keyboard (halts until entered).',
  },
  {
    word: 'LOAD',
    token: 0xef,
    kind: 'command',
    signature: 'LOAD "name"',
    doc: 'Load a program (or data) from tape.',
  },
  {
    word: 'LIST',
    token: 0xf0,
    kind: 'command',
    signature: 'LIST [line]',
    doc: 'List the program.',
  },
  {
    word: 'LET',
    token: 0xf1,
    kind: 'command',
    signature: 'LET v=expr',
    doc: 'Assignment — LET is mandatory.',
  },
  {
    word: 'PAUSE',
    token: 0xf2,
    kind: 'command',
    signature: 'PAUSE n',
    doc: 'Wait n frames (50/s); 0 = wait forever (until a key).',
  },
  {
    word: 'NEXT',
    token: 0xf3,
    kind: 'command',
    signature: 'NEXT v',
    doc: 'End of a FOR loop.',
  },
  {
    word: 'POKE',
    token: 0xf4,
    kind: 'command',
    signature: 'POKE addr,byte',
    doc: 'Write a byte of memory.',
  },
  {
    word: 'PRINT',
    token: 0xf5,
    kind: 'command',
    signature: 'PRINT [AT r,c;] items',
    doc: 'Print to the screen; ; concatenates, , tabs to the next field.',
  },
  {
    word: 'PLOT',
    token: 0xf6,
    kind: 'command',
    signature: 'PLOT x,y',
    doc: 'Set a pixel: x 0-255, y 0-175 (origin bottom-left).',
  },
  {
    word: 'RUN',
    token: 0xf7,
    kind: 'command',
    signature: 'RUN [line]',
    doc: 'Clear variables and run.',
  },
  {
    word: 'SAVE',
    token: 0xf8,
    kind: 'command',
    signature: 'SAVE "name" [LINE n]',
    doc: 'Save the program to tape (LINE n makes it auto-run).',
  },
  {
    word: 'RANDOMIZE',
    token: 0xf9,
    kind: 'command',
    signature: 'RANDOMIZE [n]',
    doc: 'Seed RND; RANDOMIZE 0 seeds from the frame counter.',
  },
  {
    word: 'IF',
    token: 0xfa,
    kind: 'command',
    signature: 'IF cond THEN statements',
    doc: 'Conditional; uses =, <, >, <=, >=, <>, AND, OR, NOT.',
  },
  {
    word: 'CLS',
    token: 0xfb,
    kind: 'command',
    signature: 'CLS',
    doc: 'Clear the screen.',
  },
  {
    word: 'DRAW',
    token: 0xfc,
    kind: 'command',
    signature: 'DRAW x,y[,angle]',
    doc: 'Draw a line (optionally an arc) relative to the last point.',
  },
  {
    word: 'CLEAR',
    token: 0xfd,
    kind: 'command',
    signature: 'CLEAR [ramtop]',
    doc: 'Delete variables (and optionally move RAMTOP).',
  },
  {
    word: 'RETURN',
    token: 0xfe,
    kind: 'command',
    signature: 'RETURN',
    doc: 'Return from GO SUB.',
  },
  {
    word: 'COPY',
    token: 0xff,
    kind: 'command',
    signature: 'COPY',
    doc: 'Print the screen to the printer.',
  },
];

/** Alias spellings accepted by the tokenizer, mapped to their canonical word. */
export const keywordAliases: Record<string, string> = {
  GOTO: 'GO TO',
  GOSUB: 'GO SUB',
};

/** Keywords sorted longest-first for greedy tokenizer matching. */
export const keywordsByLength: KeywordInfo[] = [...spectrumKeywords].sort(
  (a, b) => b.word.length - a.word.length,
);

export const keywordByToken = new Map<number, KeywordInfo>(
  spectrumKeywords.map((k) => [k.token, k]),
);

/** Statement keywords that may legally start a ZX Spectrum BASIC statement. */
export const statementKeywords = new Set(
  spectrumKeywords.filter((k) => k.kind === 'command').map((k) => k.word),
);
