import type { KeywordInfo } from '../types';

/**
 * A starter set of BBC BASIC II keywords for highlighting and autocomplete.
 * Token bytes are the genuine BASIC II values, but note that this dialect
 * does not (yet) tokenize in TypeScript — the emulator uses the BASIC ROM's
 * own tokenizer — so they currently only identify keywords to the editor.
 */
export const bbcKeywords: KeywordInfo[] = [
  // Statements
  {
    word: 'CHAIN',
    token: 0xd7,
    kind: 'command',
    signature: 'CHAIN "name"',
    doc: 'Load and run another program.',
  },
  {
    word: 'CLG',
    token: 0xda,
    kind: 'command',
    doc: 'Clear the graphics screen.',
  },
  { word: 'CLS', token: 0xdb, kind: 'command', doc: 'Clear the text screen.' },
  {
    word: 'COLOUR',
    token: 0xfb,
    kind: 'command',
    signature: 'COLOUR n',
    doc: 'Set the text colour (logical colour n; +128 sets background).',
  },
  {
    word: 'DATA',
    token: 0xdc,
    kind: 'command',
    signature: 'DATA item[,item]…',
    doc: 'Inline data for READ.',
  },
  {
    word: 'DEF',
    token: 0xdd,
    kind: 'command',
    signature: 'DEF PROCname / DEF FNname',
    doc: 'Define a procedure or function.',
  },
  {
    word: 'DIM',
    token: 0xde,
    kind: 'command',
    signature: 'DIM a(n[,m])',
    doc: 'Dimension an array.',
  },
  {
    word: 'DRAW',
    token: 0xdf,
    kind: 'command',
    signature: 'DRAW x,y',
    doc: 'Draw a line to graphics point x,y.',
  },
  { word: 'END', token: 0xe0, kind: 'command', doc: 'End the program.' },
  {
    word: 'ENDPROC',
    token: 0xe1,
    kind: 'command',
    doc: 'Return from a procedure.',
  },
  {
    word: 'ENVELOPE',
    token: 0xe2,
    kind: 'command',
    signature: 'ENVELOPE n,…(14 params)',
    doc: 'Define a sound envelope.',
  },
  {
    word: 'FOR',
    token: 0xe3,
    kind: 'command',
    signature: 'FOR v=a TO b [STEP s]',
    doc: 'Start a counted loop.',
  },
  {
    word: 'GCOL',
    token: 0xe6,
    kind: 'command',
    signature: 'GCOL mode,colour',
    doc: 'Set the graphics colour and plot mode.',
  },
  {
    word: 'GOSUB',
    token: 0xe4,
    kind: 'command',
    signature: 'GOSUB line',
    doc: 'Call a subroutine by line number.',
  },
  {
    word: 'GOTO',
    token: 0xe5,
    kind: 'command',
    signature: 'GOTO line',
    doc: 'Jump to a line number.',
  },
  {
    word: 'IF',
    token: 0xe7,
    kind: 'command',
    signature: 'IF cond THEN … [ELSE …]',
    doc: 'Conditional execution.',
  },
  {
    word: 'INPUT',
    token: 0xe8,
    kind: 'command',
    signature: 'INPUT ["prompt",] var',
    doc: 'Read a value from the keyboard.',
  },
  {
    word: 'LET',
    token: 0xe9,
    kind: 'command',
    signature: 'LET v=expr',
    doc: 'Assignment (LET is optional in BBC BASIC).',
  },
  {
    word: 'LOCAL',
    token: 0xea,
    kind: 'command',
    signature: 'LOCAL v[,v]…',
    doc: 'Declare PROC/FN-local variables.',
  },
  {
    word: 'MODE',
    token: 0xeb,
    kind: 'command',
    signature: 'MODE n',
    doc: 'Select screen mode 0–7 (7 = teletext).',
  },
  {
    word: 'MOVE',
    token: 0xec,
    kind: 'command',
    signature: 'MOVE x,y',
    doc: 'Move the graphics cursor.',
  },
  {
    word: 'NEXT',
    token: 0xed,
    kind: 'command',
    signature: 'NEXT [v]',
    doc: 'End of a FOR loop.',
  },
  {
    word: 'ON',
    token: 0xee,
    kind: 'command',
    signature: 'ON n GOTO/GOSUB …',
    doc: 'Computed jump.',
  },
  {
    word: 'PLOT',
    token: 0xf0,
    kind: 'command',
    signature: 'PLOT k,x,y',
    doc: 'General graphics plot.',
  },
  {
    word: 'PRINT',
    token: 0xf1,
    kind: 'command',
    signature: "PRINT [TAB(x,y)][expr][;,']",
    doc: 'Print to the screen.',
  },
  {
    word: 'PROC',
    token: 0xf2,
    kind: 'command',
    signature: 'PROCname[(args)]',
    doc: 'Call a named procedure.',
  },
  {
    word: 'READ',
    token: 0xf3,
    kind: 'command',
    signature: 'READ var[,var]…',
    doc: 'Read the next DATA item.',
  },
  {
    word: 'REM',
    token: 0xf4,
    kind: 'command',
    signature: 'REM comment',
    doc: 'Comment line.',
  },
  {
    word: 'REPEAT',
    token: 0xf5,
    kind: 'command',
    doc: 'Start a REPEAT…UNTIL loop.',
  },
  {
    word: 'RESTORE',
    token: 0xf7,
    kind: 'command',
    signature: 'RESTORE [line]',
    doc: 'Reset the DATA pointer.',
  },
  { word: 'RETURN', token: 0xf8, kind: 'command', doc: 'Return from a GOSUB.' },
  { word: 'RUN', token: 0xf9, kind: 'command', doc: 'Run the program.' },
  {
    word: 'SOUND',
    token: 0xd4,
    kind: 'command',
    signature: 'SOUND chan,amp,pitch,dur',
    doc: 'Make a sound.',
  },
  {
    word: 'STOP',
    token: 0xfa,
    kind: 'command',
    doc: 'Stop with an error report.',
  },
  {
    word: 'UNTIL',
    token: 0xfd,
    kind: 'command',
    signature: 'UNTIL cond',
    doc: 'End of a REPEAT loop.',
  },
  {
    word: 'VDU',
    token: 0xef,
    kind: 'command',
    signature: 'VDU n[,n]…',
    doc: 'Send bytes to the VDU driver.',
  },
  // Structure words
  {
    word: 'ELSE',
    token: 0x8b,
    kind: 'command',
    doc: 'Alternative branch of IF…THEN.',
  },
  { word: 'STEP', token: 0x88, kind: 'command', doc: 'Loop increment in FOR.' },
  {
    word: 'THEN',
    token: 0x8c,
    kind: 'command',
    doc: 'Follows the condition in IF.',
  },
  { word: 'TO', token: 0xb8, kind: 'command', doc: 'Loop limit in FOR.' },
  // Operators
  { word: 'AND', token: 0x80, kind: 'operator', doc: 'Bitwise/logical AND.' },
  { word: 'DIV', token: 0x81, kind: 'operator', doc: 'Integer division.' },
  { word: 'EOR', token: 0x82, kind: 'operator', doc: 'Bitwise exclusive OR.' },
  { word: 'MOD', token: 0x83, kind: 'operator', doc: 'Integer remainder.' },
  { word: 'NOT', token: 0xac, kind: 'operator', doc: 'Logical/bitwise NOT.' },
  { word: 'OR', token: 0x84, kind: 'operator', doc: 'Bitwise/logical OR.' },
  // Functions
  {
    word: 'ABS',
    token: 0x94,
    kind: 'function',
    signature: 'ABS(n)',
    doc: 'Absolute value.',
  },
  {
    word: 'ASC',
    token: 0x97,
    kind: 'function',
    signature: 'ASC(a$)',
    doc: 'Character code of the first character.',
  },
  {
    word: 'ATN',
    token: 0x99,
    kind: 'function',
    signature: 'ATN(n)',
    doc: 'Arctangent (radians).',
  },
  {
    word: 'CHR$',
    token: 0xbd,
    kind: 'function',
    signature: 'CHR$(n)',
    doc: 'Character with code n.',
  },
  {
    word: 'COS',
    token: 0x9b,
    kind: 'function',
    signature: 'COS(n)',
    doc: 'Cosine (radians).',
  },
  {
    word: 'EXP',
    token: 0xa1,
    kind: 'function',
    signature: 'EXP(n)',
    doc: 'e to the power n.',
  },
  {
    word: 'FN',
    token: 0xa4,
    kind: 'function',
    signature: 'FNname[(args)]',
    doc: 'Call a named function.',
  },
  {
    word: 'GET',
    token: 0xa5,
    kind: 'function',
    doc: 'Wait for a key, return its code.',
  },
  {
    word: 'GET$',
    token: 0xbe,
    kind: 'function',
    doc: 'Wait for a key, return it as a string.',
  },
  {
    word: 'INKEY',
    token: 0xa6,
    kind: 'function',
    signature: 'INKEY(t)',
    doc: 'Read a key with timeout t centiseconds (-1 if none).',
  },
  {
    word: 'INKEY$',
    token: 0xbf,
    kind: 'function',
    signature: 'INKEY$(t)',
    doc: 'Read a key as a string ("" if none) — game input.',
  },
  {
    word: 'INSTR',
    token: 0xa7,
    kind: 'function',
    signature: 'INSTR(a$,b$[,start])',
    doc: 'Find b$ within a$.',
  },
  {
    word: 'INT',
    token: 0xa8,
    kind: 'function',
    signature: 'INT(n)',
    doc: 'Round towards minus infinity.',
  },
  {
    word: 'LEFT$',
    token: 0xc0,
    kind: 'function',
    signature: 'LEFT$(a$,n)',
    doc: 'Leftmost n characters.',
  },
  {
    word: 'LEN',
    token: 0xa9,
    kind: 'function',
    signature: 'LEN(a$)',
    doc: 'String length.',
  },
  {
    word: 'LN',
    token: 0xaa,
    kind: 'function',
    signature: 'LN(n)',
    doc: 'Natural logarithm.',
  },
  {
    word: 'LOG',
    token: 0xab,
    kind: 'function',
    signature: 'LOG(n)',
    doc: 'Base-10 logarithm.',
  },
  {
    word: 'MID$',
    token: 0xc1,
    kind: 'function',
    signature: 'MID$(a$,start[,len])',
    doc: 'Substring.',
  },
  { word: 'PI', token: 0xaf, kind: 'function', doc: 'The constant π.' },
  {
    word: 'POINT',
    token: 0xb0,
    kind: 'function',
    signature: 'POINT(x,y)',
    doc: 'Logical colour at graphics point x,y.',
  },
  { word: 'POS', token: 0xb1, kind: 'function', doc: 'Text cursor column.' },
  {
    word: 'RIGHT$',
    token: 0xc2,
    kind: 'function',
    signature: 'RIGHT$(a$,n)',
    doc: 'Rightmost n characters.',
  },
  {
    word: 'RND',
    token: 0xb3,
    kind: 'function',
    signature: 'RND[(n)]',
    doc: 'Random number: RND(n) gives 1..n.',
  },
  {
    word: 'SGN',
    token: 0xb4,
    kind: 'function',
    signature: 'SGN(n)',
    doc: 'Sign of n (-1, 0, 1).',
  },
  {
    word: 'SIN',
    token: 0xb5,
    kind: 'function',
    signature: 'SIN(n)',
    doc: 'Sine (radians).',
  },
  {
    word: 'SQR',
    token: 0xb6,
    kind: 'function',
    signature: 'SQR(n)',
    doc: 'Square root.',
  },
  {
    word: 'STR$',
    token: 0xc3,
    kind: 'function',
    signature: 'STR$(n)',
    doc: 'Number as a string.',
  },
  {
    word: 'STRING$',
    token: 0xc4,
    kind: 'function',
    signature: 'STRING$(n,a$)',
    doc: 'a$ repeated n times.',
  },
  {
    word: 'TAB',
    token: 0x8a,
    kind: 'function',
    signature: 'TAB(x[,y])',
    doc: 'Position the cursor within PRINT.',
  },
  {
    word: 'TAN',
    token: 0xb7,
    kind: 'function',
    signature: 'TAN(n)',
    doc: 'Tangent (radians).',
  },
  {
    word: 'TIME',
    token: 0x91,
    kind: 'function',
    doc: 'Centisecond timer (read/write).',
  },
  {
    word: 'VAL',
    token: 0xbb,
    kind: 'function',
    signature: 'VAL(a$)',
    doc: 'Numeric value of a string.',
  },
  { word: 'VPOS', token: 0xbc, kind: 'function', doc: 'Text cursor row.' },
];
