import type { KeywordInfo } from '../types';

/**
 * The ZX81 BASIC keyword/token table (tokens 0x40–0x42 and 0xC1–0xFF).
 * Token 0xC0 is the quote-image character, handled by the tokenizer inside
 * strings ("" → 0xC0), so it is not listed here.
 */
export const zx81Keywords: KeywordInfo[] = [
  // Expression keywords living in the character set area
  {
    word: 'RND',
    token: 0x40,
    kind: 'function',
    signature: 'RND',
    doc: 'Random number in [0,1). Seed with RAND.',
  },
  {
    word: 'INKEY$',
    token: 0x41,
    kind: 'function',
    signature: 'INKEY$',
    doc: 'Currently pressed key as a string, "" if none. The heart of every game loop.',
  },
  {
    word: 'PI',
    token: 0x42,
    kind: 'function',
    signature: 'PI',
    doc: '3.14159265…',
  },

  // 0xC1 –
  {
    word: 'AT',
    token: 0xc1,
    kind: 'operator',
    signature: 'PRINT AT row,col;',
    doc: 'Position the print cursor: row 0-21, column 0-31.',
  },
  {
    word: 'TAB',
    token: 0xc2,
    kind: 'operator',
    signature: 'PRINT TAB n;',
    doc: 'Move print position to column n.',
  },
  {
    word: 'CODE',
    token: 0xc4,
    kind: 'function',
    signature: 'CODE s$',
    doc: 'ZX81 character code of the first character of s$.',
  },
  {
    word: 'VAL',
    token: 0xc5,
    kind: 'function',
    signature: 'VAL s$',
    doc: 'Evaluate s$ as a numeric expression.',
  },
  {
    word: 'LEN',
    token: 0xc6,
    kind: 'function',
    signature: 'LEN s$',
    doc: 'Length of string s$.',
  },
  {
    word: 'SIN',
    token: 0xc7,
    kind: 'function',
    signature: 'SIN x',
    doc: 'Sine (radians).',
  },
  {
    word: 'COS',
    token: 0xc8,
    kind: 'function',
    signature: 'COS x',
    doc: 'Cosine (radians).',
  },
  {
    word: 'TAN',
    token: 0xc9,
    kind: 'function',
    signature: 'TAN x',
    doc: 'Tangent (radians).',
  },
  {
    word: 'ASN',
    token: 0xca,
    kind: 'function',
    signature: 'ASN x',
    doc: 'Arcsine.',
  },
  {
    word: 'ACS',
    token: 0xcb,
    kind: 'function',
    signature: 'ACS x',
    doc: 'Arccosine.',
  },
  {
    word: 'ATN',
    token: 0xcc,
    kind: 'function',
    signature: 'ATN x',
    doc: 'Arctangent.',
  },
  {
    word: 'LN',
    token: 0xcd,
    kind: 'function',
    signature: 'LN x',
    doc: 'Natural logarithm.',
  },
  {
    word: 'EXP',
    token: 0xce,
    kind: 'function',
    signature: 'EXP x',
    doc: 'e to the power x.',
  },
  {
    word: 'INT',
    token: 0xcf,
    kind: 'function',
    signature: 'INT x',
    doc: 'Largest integer ≤ x (floors negatives).',
  },
  {
    word: 'SQR',
    token: 0xd0,
    kind: 'function',
    signature: 'SQR x',
    doc: 'Square root.',
  },
  {
    word: 'SGN',
    token: 0xd1,
    kind: 'function',
    signature: 'SGN x',
    doc: 'Sign of x: -1, 0 or 1.',
  },
  {
    word: 'ABS',
    token: 0xd2,
    kind: 'function',
    signature: 'ABS x',
    doc: 'Absolute value.',
  },
  {
    word: 'PEEK',
    token: 0xd3,
    kind: 'function',
    signature: 'PEEK addr',
    doc: 'Read a byte of memory. PEEK 16396+256*PEEK 16397 = D_FILE.',
  },
  {
    word: 'USR',
    token: 0xd4,
    kind: 'function',
    signature: 'USR addr',
    doc: 'Call machine code at addr; returns BC.',
  },
  {
    word: 'STR$',
    token: 0xd5,
    kind: 'function',
    signature: 'STR$ x',
    doc: 'Number as a string.',
  },
  {
    word: 'CHR$',
    token: 0xd6,
    kind: 'function',
    signature: 'CHR$ n',
    doc: 'Character with ZX81 code n (NOT ASCII).',
  },
  {
    word: 'NOT',
    token: 0xd7,
    kind: 'function',
    signature: 'NOT x',
    doc: 'Logical not: 1 if x=0, else 0.',
  },
  {
    word: '**',
    token: 0xd8,
    kind: 'operator',
    signature: 'x ** y',
    doc: 'Power. The ZX81 uses ** rather than ^.',
  },
  {
    word: 'OR',
    token: 0xd9,
    kind: 'operator',
    signature: 'a OR b',
    doc: 'Logical or.',
  },
  {
    word: 'AND',
    token: 0xda,
    kind: 'operator',
    signature: 'a AND b',
    doc: 'Logical and.',
  },
  {
    word: '<=',
    token: 0xdb,
    kind: 'operator',
    doc: 'Less than or equal — a single ZX81 token.',
  },
  {
    word: '>=',
    token: 0xdc,
    kind: 'operator',
    doc: 'Greater than or equal — a single ZX81 token.',
  },
  {
    word: '<>',
    token: 0xdd,
    kind: 'operator',
    doc: 'Not equal — a single ZX81 token.',
  },
  {
    word: 'THEN',
    token: 0xde,
    kind: 'operator',
    signature: 'IF cond THEN statement',
    doc: 'One statement only — the ZX81 has no ELSE and no multi-statement lines.',
  },
  {
    word: 'TO',
    token: 0xdf,
    kind: 'operator',
    signature: 'FOR v=a TO b | s$(a TO b)',
    doc: 'FOR range or string slice.',
  },
  {
    word: 'STEP',
    token: 0xe0,
    kind: 'operator',
    signature: 'FOR v=a TO b STEP c',
    doc: 'FOR loop increment.',
  },

  // Statement keywords
  {
    word: 'LPRINT',
    token: 0xe1,
    kind: 'command',
    signature: 'LPRINT items',
    doc: 'Print to the ZX printer.',
  },
  {
    word: 'LLIST',
    token: 0xe2,
    kind: 'command',
    signature: 'LLIST [line]',
    doc: 'List program to the ZX printer.',
  },
  {
    word: 'STOP',
    token: 0xe3,
    kind: 'command',
    signature: 'STOP',
    doc: 'Halt with report 9; CONT resumes.',
  },
  {
    word: 'SLOW',
    token: 0xe4,
    kind: 'command',
    signature: 'SLOW',
    doc: 'Compute-and-display mode: screen stays on, ~4x slower.',
  },
  {
    word: 'FAST',
    token: 0xe5,
    kind: 'command',
    signature: 'FAST',
    doc: 'Display off while computing; screen flickers on input/PAUSE.',
  },
  {
    word: 'NEW',
    token: 0xe6,
    kind: 'command',
    signature: 'NEW',
    doc: 'Erase the program.',
  },
  {
    word: 'SCROLL',
    token: 0xe7,
    kind: 'command',
    signature: 'SCROLL',
    doc: 'Scroll the display up one line. Needed before printing on a full screen.',
  },
  {
    word: 'CONT',
    token: 0xe8,
    kind: 'command',
    signature: 'CONT',
    doc: 'Continue after STOP/BREAK.',
  },
  {
    word: 'DIM',
    token: 0xe9,
    kind: 'command',
    signature: 'DIM A(n) | DIM A$(n,m)',
    doc: 'Declare an array. Array names are a single letter.',
  },
  {
    word: 'REM',
    token: 0xea,
    kind: 'command',
    signature: 'REM comment',
    doc: 'Comment line (also a common stash for machine code).',
  },
  {
    word: 'FOR',
    token: 0xeb,
    kind: 'command',
    signature: 'FOR v=a TO b [STEP c]',
    doc: 'Loop. Control variable is a single letter.',
  },
  {
    word: 'GOTO',
    token: 0xec,
    kind: 'command',
    signature: 'GOTO line',
    doc: 'Jump to line number (computed targets allowed).',
  },
  {
    word: 'GOSUB',
    token: 0xed,
    kind: 'command',
    signature: 'GOSUB line',
    doc: 'Call subroutine; RETURN comes back.',
  },
  {
    word: 'INPUT',
    token: 0xee,
    kind: 'command',
    signature: 'INPUT v',
    doc: 'Read a value from the keyboard (stops the program; use INKEY$ in games).',
  },
  {
    word: 'LOAD',
    token: 0xef,
    kind: 'command',
    signature: 'LOAD "name"',
    doc: 'Load a program from tape.',
  },
  {
    word: 'LIST',
    token: 0xf0,
    kind: 'command',
    signature: 'LIST [line]',
    doc: 'List the program.',
  },
  {
    word: 'LET',
    token: 0xf1,
    kind: 'command',
    signature: 'LET v=expr',
    doc: 'Assignment — LET is mandatory on the ZX81.',
  },
  {
    word: 'PAUSE',
    token: 0xf2,
    kind: 'command',
    signature: 'PAUSE n',
    doc: 'Wait n frames (50/s) or until a key; 32768+ = forever. POKE 16437,255 after PAUSE avoids a display glitch.',
  },
  {
    word: 'NEXT',
    token: 0xf3,
    kind: 'command',
    signature: 'NEXT v',
    doc: 'End of FOR loop.',
  },
  {
    word: 'POKE',
    token: 0xf4,
    kind: 'command',
    signature: 'POKE addr,byte',
    doc: 'Write a byte of memory.',
  },
  {
    word: 'PRINT',
    token: 0xf5,
    kind: 'command',
    signature: 'PRINT [AT r,c;] items',
    doc: 'Print to the screen; , tabs to a 16-column field, ; concatenates.',
  },
  {
    word: 'PLOT',
    token: 0xf6,
    kind: 'command',
    signature: 'PLOT x,y',
    doc: 'Set a pixel block: x 0-63, y 0-43 (origin bottom-left).',
  },
  {
    word: 'RUN',
    token: 0xf7,
    kind: 'command',
    signature: 'RUN [line]',
    doc: 'Clear variables and run.',
  },
  {
    word: 'SAVE',
    token: 0xf8,
    kind: 'command',
    signature: 'SAVE "name"',
    doc: 'Save the program to tape.',
  },
  {
    word: 'RAND',
    token: 0xf9,
    kind: 'command',
    signature: 'RAND [n]',
    doc: 'Seed RND; RAND 0 seeds from the frame counter.',
  },
  {
    word: 'IF',
    token: 0xfa,
    kind: 'command',
    signature: 'IF cond THEN statement',
    doc: 'Conditional; condition uses =, <, >, <=, >=, <>, AND, OR, NOT.',
  },
  {
    word: 'CLS',
    token: 0xfb,
    kind: 'command',
    signature: 'CLS',
    doc: 'Clear the screen.',
  },
  {
    word: 'UNPLOT',
    token: 0xfc,
    kind: 'command',
    signature: 'UNPLOT x,y',
    doc: 'Clear a pixel block set by PLOT.',
  },
  {
    word: 'CLEAR',
    token: 0xfd,
    kind: 'command',
    signature: 'CLEAR',
    doc: 'Delete all variables.',
  },
  {
    word: 'RETURN',
    token: 0xfe,
    kind: 'command',
    signature: 'RETURN',
    doc: 'Return from GOSUB.',
  },
  {
    word: 'COPY',
    token: 0xff,
    kind: 'command',
    signature: 'COPY',
    doc: 'Print the screen to the ZX printer.',
  },
];

/** Keywords sorted longest-first for greedy tokenizer matching. */
export const keywordsByLength: KeywordInfo[] = [...zx81Keywords].sort(
  (a, b) => b.word.length - a.word.length,
);

export const keywordByToken = new Map<number, KeywordInfo>(
  zx81Keywords.map((k) => [k.token, k]),
);

/** Statement keywords that may legally start a ZX81 BASIC line. */
export const statementKeywords = new Set(
  zx81Keywords.filter((k) => k.kind === 'command').map((k) => k.word),
);
